# Generated by Django 2.2.14 on 2020-09-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200902_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('S', 'Rolex'), ('RM', 'Richard Mille'), ('H', 'Hublot'), ('FM', 'Frank Muller'), ('AP', 'Audemars Piguet'), ('P', 'Patek Phillipe'), ('Z', 'Zenith'), ('B', 'Breitling'), ('C', 'Constantin'), ('O', 'Omega'), ('M', 'Montblanc'), ('V', 'Versace'), ('C', 'Cartier'), ('JL', 'Jaeger Lecoultre'), ('JC', 'Jacob and Co'), ('Co', 'Corum'), ('J', 'Jeweleries'), ('I', 'IWC')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Catergories',
            },
        ),
    ]
