# Generated by Django 2.2.14 on 2020-09-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_name',
            field=models.CharField(choices=[('S', 'Sale'), ('N', 'New'), ('L', 'Limited Edition')], default='New', max_length=2),
            preserve_default=False,
        ),
    ]
